### ISSUE TITLE
Where is the results?

### ISSUE THREAD

**Issue by victordiao** [karlmoritz/bicvm#11]
Hi, 
I use the ./dbltrain to learns embeddings given two files of parallel, sentence aligned text
I wonder where can I see the results?
Can I get the bilingual vectors?

Thanks!

**Comment by karlmoritz** [comment]
Use the extract-vectors binary for this, passing in the trained model and optionally a list of words you would like to extract vectors from. Depending on onward usage you can also look at that file for inspiration on how to use these vectors in other places.
