### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by sanjanasri** [karlmoritz/bicvm#6]
Hi,

When I try to run make fiel. I am getting error as 

error: narrowing conversion of ‘9223372039002259456ull’ from ‘long long unsigned int’ to ‘long long int’ inside { } [-Wnarrowing]

Please help

**Comment by AzizCode92** [comment]
Change this file "fastonebigheader.h" 
and add this line : 
#define v4sil(x) v2dil((((long long) (x)) << 32) | (x))

**Comment by karlmoritz** [comment]
Updated code base to include this fix. Thanks for pointing this out!
